backend:
  name: github
  repo: dralucard666/demo-static-page
  branch: main
  base_url: https://decap-proxy.jonasbrossmann80.workers.dev
  auth_endpoint: /auth

media_folder: "src/images"
public_folder: "/demo-static-page/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "src/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "about"
        label: "About Page"
        file: "src/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
